### PR TITLE
feat: signup page integrated

### PR DESCRIPTION
**Pull request by prakash855**
Signup page integrated!

### CODE REVIEW

**Review by Ayushi20-19 — APPROVED** [review]

**Comment by vermasavita** [comment]
> ✔️ Deploy Preview for _peaceful-dijkstra-213a7d_ ready!
> 
> 🔨 Explore the source changes: [8d6b3f0](https://github.com/prakash855/eBuy/commit/8d6b3f06064b0cc9aa05a4fd5ae8ba4ab8fd85ff)
> 
> 🔍 Inspect the deploy log: https://app.netlify.com/sites/peaceful-dijkstra-213a7d/deploys/620f70b01ca7ea0008d9dcfd
> 
> 😎 Browse the preview: https://deploy-preview-3--peaceful-dijkstra-213a7d.netlify.app
 
I can't see any page in the last link.

**Review by Ayushi20-19 — COMMENTED** [review]
Browse the preview: https://deploy-preview-3--peaceful-dijkstra-213a7d.netlify.app/ 
link is not working?

**Review by vermasavita — APPROVED** [review]

**Comment by prakash855** [comment]
> > ✔️ Deploy Preview for _peaceful-dijkstra-213a7d_ ready!
> > 🔨 Explore the source changes: [8d6b3f0](https://github.com/prakash855/eBuy/commit/8d6b3f06064b0cc9aa05a4fd5ae8ba4ab8fd85ff)
> > 🔍 Inspect the deploy log: https://app.netlify.com/sites/peaceful-dijkstra-213a7d/deploys/620f70b01ca7ea0008d9dcfd
> > 😎 Browse the preview: https://deploy-preview-3--peaceful-dijkstra-213a7d.netlify.app
> 
> I can't see any page in the last link.



> Browse the preview: https://deploy-preview-3--peaceful-dijkstra-213a7d.netlify.app/ link is not working?

maybe because I just changed my hostname

**Comment by prakash855** [comment]
> Browse the preview: https://deploy-preview-3--peaceful-dijkstra-213a7d.netlify.app/ link is not working?

maybe because I just changed my hostname

**Pull request merged**
